package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2018_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'ChatService_HttpsGithubComMissingdaysChatServiceRefsHeadsMaster'
in the project with id = 'ChatService', and delete the patch script.
*/
create(RelativeId("ChatService"), GitVcsRoot({
    id("ChatService_HttpsGithubComMissingdaysChatServiceRefsHeadsMaster")
    name = "https://github.com/missingdays/ChatService#refs/heads/master"
    url = "https://github.com/missingdays/ChatService"
    authMethod = password {
        userName = "missingdays"
        password = "credentialsJSON:c02562c7-d8af-44ca-a17d-ffc3799dd71b"
    }
}))

